### ISSUE TITLE
kubectl provider 

### ISSUE THREAD

**Issue by joshuaganger** [kjpark/terraform-aws-eks-vpc-cni-custom-networking#1]
I'm trying to incorporate your module into a larger configuration and running into an issue that the module configures the kubectl provider differently than required in my context.  It seems that Terraform specifically disallows overriding module provider configuration - it has functionality to explicitly pass a provider config, but when I try I get "Error: Cannot override provider configuration".  

Any chance you'd consider removing the provider configuration from this module?  Otherwise I think my only choice is to fork it.

I'm open to suggestions if you have other ideas!

**Comment by kjpark** [comment]
Interesting, out of curiosity what provider are you trying to incorporate? But do feel free to fork and PR if you feel it would help your use case

**Comment by joshuaganger** [comment]
Still using "gavinbunney/kubectl" provider, but configured with load_config_file = false, and host, token and cluster_ca_certificate pulled from data blocks referencing the cluster and cluster auth, rather than using a kubeconfig file as you have done.  

In general I've read that it's preferable not to include a provider definition inside modules, but allow them to be configured in the parent, and inferred (or passed explicitly).

**Comment by kjpark** [comment]
I agree and think it's a good change. However I don't have a testing environment to develop this currently to make sure the changes work properly. If you wouldn't mind making and testing the change, I'd love to accept a PR!

**Comment by kjpark** [comment]
provider configuration removed in v0.1.1. thanks for the suggestion.
